language: node_js
node_js:
  - 6.3.0
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - npm install
  - bower install
script: grunt
cache:
  directories:
    - node_modules
notifications:
  email:
    on_failure: change
after_success:
  - bash ./deploy.sh
